const express = require('express')
const productRouter = express.Router()
const productController = require('../controllers/productController')
const authentication = require('../middleware/authentication')
const authorizationUser = require('../middleware/authorization')
const userController = require('../controllers/userController')

productRouter.get('/category', productController.getCategory)
productRouter.get('/product', productController.getProduct)
productRouter.get('/product/:id', productController.getProductId)
productRouter.get('/productSlug/:slug', productController.getProductSlug)
productRouter.use(authentication)
productRouter.post('/register', userController.registerUser)
productRouter.post('/category', productController.addCategory)
productRouter.post('/product', productController.createProduct)
productRouter.get('/photoId/:id', productController.getPhotoById)
productRouter.get('/photo/:id', productController.getPhoto) // get all photo based on productId
productRouter.get('/category/:id', productController.getCategoryId)
productRouter.delete('/category/:id', productController.deleteCategory)
productRouter.delete('/photo/:id', productController.deletePhoto)
productRouter.delete('/product/:id', authorizationUser, productController.deleteProduct)
productRouter.put('/category/:id', productController.updateCategory)
productRouter.put('/photo/:id', productController.updatePhoto)
productRouter.put('/product/:id', authorizationUser, productController.updateProduct)
module.exports = productRouter